trigger:
  - main

variables:
  - name: DOCKER_IMAGE
    value: 'spring-boot-builder:latest'
  - name: DOCKER_PLATFORM
    value: 'linux/amd64'

pool:
  name: 'Default'

stages:
  - stage: Build
    displayName: Build and Test
    jobs:
      - job: BuildAndTest
        displayName: Build and Test
        steps:
          - script: |
              docker build -t $(DOCKER_IMAGE) --platform $(DOCKER_PLATFORM) -f app/Dockerfile .
            displayName: 'Build Docker Image'
          - script: |
              docker run --rm \
                --platform $(DOCKER_PLATFORM) \
                $(DOCKER_IMAGE) \
                /bin/bash -c "cd /app && ./mvnw spotbugs:check checkstyle:check pmd:check"
            displayName: 'Run Static Analysis'
            continueOnError: 'true'

  - stage: Release
    displayName: Release Stage
    dependsOn: Build
    jobs:
      - template: .azure-pipelines/templates/release.yml
        parameters:
          jarName: 'demo-0.0.1-SNAPSHOT.jar'