trigger:
  - main

variables:
  - name: DOCKER_IMAGE
    value: 'spring-boot-builder:latest'
  - name: DOCKER_PLATFORM
    value: 'linux/amd64'

pool:
  name: 'Default'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - script: |
              docker build -t $(DOCKER_IMAGE) --platform $(DOCKER_PLATFORM) -f app/Dockerfile .
            displayName: 'Build Docker Image'

  - stage: SAST
    displayName: Static Analysis
    dependsOn: Build
    jobs:
      - template: .azure-pipelines/templates/sast.yml
        parameters:
          dockerImage: $(DOCKER_IMAGE)
          platform: $(DOCKER_PLATFORM)

  - stage: Release
    displayName: Release Stage
    dependsOn: SAST
    jobs:
      - template: .azure-pipelines/templates/release.yml
        parameters:
          jarName: 'demo-0.0.1-SNAPSHOT.jar'