trigger:
  - main

variables:
  - name: DOCKER_IMAGE
    value: 'spring-boot-builder:latest'
  - name: JAR_NAME
    value: 'app.jar'
  - name: DOCKER_PLATFORM
    value: 'linux/amd64'

pool:
  name: 'Default'

stages:
  - stage: BuildImage
    displayName: Build Docker Image
    jobs:
      - job: BuildDockerImage
        displayName: Build Docker Image
        steps:
          - script: |
              docker build -t $(DOCKER_IMAGE) --platform $(DOCKER_PLATFORM) -f app/Dockerfile .
            displayName: 'Build Docker Image'

  - stage: Build
    displayName: Build Stage
    dependsOn: BuildImage
    jobs:
      - template: .azure-pipelines/templates/build.yml
        parameters:
          dockerImage: $(DOCKER_IMAGE)
          jarName: $(JAR_NAME)
          platform: $(DOCKER_PLATFORM)

  - stage: SAST
    displayName: Static Analysis Stage
    dependsOn: Build
    jobs:
      - template: .azure-pipelines/templates/sast.yml
        parameters:
          dockerImage: $(DOCKER_IMAGE)
          platform: $(DOCKER_PLATFORM)

  - stage: Release
    displayName: Release Stage
    dependsOn: SAST
    jobs:
      - template: .azure-pipelines/templates/release.yml
        parameters:
          jarName: $(JAR_NAME)