parameters:
  - name: dockerImage
    type: string
  - name: jarName
    type: string
  - name: platform
    type: string

jobs:
  - job: Build
    displayName: Build with Docker
    steps:
      - script: |
          ls -l app/
        displayName: 'List app directory'
      - script: |
          ls -l app/target/
        displayName: 'List target directory'
      - script: |
          docker run --rm \
            --platform ${{ parameters.platform }} \
            -v $(pwd)/app:/app \
            ${{ parameters.dockerImage }} \
            /bin/bash -c "cd /app && ls -la && ./mvnw clean package -DskipTests && ls -la target/"
        displayName: 'Build JAR with Docker'
      - script: |
          ls -lh app/target/
        displayName: 'List build artifacts'
      - script: |
          if [ -f "app/target/${{ parameters.jarName }}" ]; then
            echo "JAR file found at app/target/${{ parameters.jarName }}"
            echo "##vso[task.setvariable variable=JAR_PATH]$(pwd)/app/target/${{ parameters.jarName }}"
          else
            echo "JAR file not found at app/target/${{ parameters.jarName }}"
            echo "##vso[task.logissue type=error]JAR file not found"
            exit 1
          fi
        displayName: 'Set JAR path variable'