parameters:
  - name: dockerImage
    type: string
  - name: jarName
    type: string
  - name: platform
    type: string

jobs:
  - job: Build
    displayName: Build with Docker
    steps:
      - script: |
          ls -l
      - script: |
          docker run --rm --platform ${{ parameters.platform }} -v $(pwd):/app --workdir /app ${{ parameters.dockerImage }} bash -c "apt-get update && apt-get install -y tar curl maven && mvn clean package -DskipTests"
        displayName: 'Build JAR with Docker'
      - script: |
          ls -lh target/
        displayName: 'List build artifacts'
      - script: |
          echo "##vso[task.setvariable variable=JAR_PATH]$(pwd)/target/${{ parameters.jarName }}"
        displayName: 'Set JAR path variable'