parameters:
  dockerImage: ''
  platform: ''

jobs:
  - job: SAST
    displayName: 'Static Application Security Testing'
    timeoutInMinutes: 10
    steps:
      # Run Maven with SpotBugs, Checkstyle, and PMD
      - script: |
          docker run --rm \
            --platform ${{ parameters.platform }} \
            ${{ parameters.dockerImage }} \
            /bin/bash -c "cd /app && ./mvnw spotbugs:check -Dspotbugs.failOnError=false"
        displayName: 'Run SpotBugs'
        continueOnError: 'true'
        timeoutInMinutes: 1

      - script: |
          docker run --rm \
            --platform ${{ parameters.platform }} \
            ${{ parameters.dockerImage }} \
            /bin/bash -c "cd /app && ./mvnw checkstyle:check -Dcheckstyle.failOnViolation=false"
        displayName: 'Run Checkstyle'
        continueOnError: 'true'
        timeoutInMinutes: 1

      - script: |
          docker run --rm \
            --platform ${{ parameters.platform }} \
            ${{ parameters.dockerImage }} \
            /bin/bash -c "cd /app && ./mvnw pmd:check -Dpmd.failOnViolation=false"
        displayName: 'Run PMD'
        continueOnError: 'true'
        timeoutInMinutes: 1
      
      # Display SpotBugs results
      - script: |
          if [ -f "app/target/spotbugsXml.xml" ]; then
            echo "##[section]SpotBugs Results"
            cat app/target/spotbugsXml.xml
          fi
        displayName: 'Display SpotBugs Results'
        condition: succeededOrFailed()
      
      # Display Checkstyle results
      - script: |
          if [ -f "app/target/checkstyle-result.xml" ]; then
            echo "##[section]Checkstyle Results"
            cat app/target/checkstyle-result.xml
          fi
        displayName: 'Display Checkstyle Results'
        condition: succeededOrFailed()
      
      # Display PMD results
      - script: |
          if [ -f "app/target/pmd.xml" ]; then
            echo "##[section]PMD Results"
            cat app/target/pmd.xml
          fi
        displayName: 'Display PMD Results'
        condition: succeededOrFailed()
      
      - script: |
          echo "##vso[task.setvariable variable=SAST_STATUS]success"
        displayName: 'Set SAST status'
        condition: succeeded()
      # Optionally, add a tool like SpotBugs or Checkstyle here