parameters:
  - name: dockerImage
    type: string
  - name: platform
    type: string

jobs:
  - job: SAST
    displayName: Static Code Analysis
    steps:
      - script: |
          docker run --rm --platform ${{ parameters.platform }} -v $(pwd):/app --workdir /app ${{ parameters.dockerImage }} bash -c "apt-get update && apt-get install -y tar curl maven && mvn verify -DskipTests"
        displayName: 'Run Maven Verify (SAST)'
      - script: |
          echo "##vso[task.setvariable variable=SAST_STATUS]success"
        displayName: 'Set SAST status'
        condition: succeeded()
      # Optionally, add a tool like SpotBugs or Checkstyle here